// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChoicesController from "./choices_controller"
application.register("choices", ChoicesController)

import EditableController from "./editable_controller"
application.register("editable", EditableController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TabulatorController from "./tabulator_controller"
application.register("tabulator", TabulatorController)
