// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import DashboardsController from "./dashboards_controller"
application.register("dashboards", DashboardsController)

import EditableController from "./editable_controller"
application.register("editable", EditableController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SlimSelectController from "./slim_select_controller"
application.register("slim-select", SlimSelectController)

import TabulatorController from "./tabulator_controller"
application.register("tabulator", TabulatorController)

import VisualizationController from "./visualization_controller"
application.register("visualization", VisualizationController)
