name: Kamal

on:
  push:
    branches:
      - master
jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      image: ${{ steps.build.outputs.image }}
    env:
      RAILS_ENV: production
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region           : us-east-1
#          mask-aws-account-id  : 'no'
#
#      - name: Login to Amazon ECR
#        id  : login-ecr
#        uses: aws-actions/amazon-ecr-login@v1
#
#      - name: Kamal Envify
#        id  : kamal-envify
#        env :
#          KAMAL_REGISTRY_PASSWORD: ${{ steps.login-ecr.outputs.docker_password_<YOUR_AWS_ACCOUNT_ID>_dkr_ecr_<YOUR_AWS_REGION>_amazonaws_com }}
#          DATABASE_URL: ${{ secrets.DATABASE_URL }}
#          REDIS_URL: ${{ secrets.REDIS_URL }}
#          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
#          DOCKER_BUILDKIT: 1
#        run: kamal envify
#
#      - name: Kamal Deploy
#        id: kamal-deploy
#        run: kamal deploy